### ISSUE TITLE
Assign a Wiki ID for every object (article)

### ISSUE THREAD

**Issue by Geno1024** [AlexanderMisel/LuaWiki#10]
A Wiki ID (WID) can be assigned for every object in a (in production) LuaWiki server, if accepted.

Similar to "inode" in Ext filesystem, WID can be used for wiki locating (file retrieving), redirection (soft / hard link), etc.

An incomplete example "specification" of WID can be this:

1. WID is a 128 bit integer.
1.1. WID has three kinds of representation:
1.1.1. WID can be represented as 4 `int32`.
1.1.2. WID can be represented LIKE a `UUID`, or a hexadecimal string of length 32.
1.1.3. WID can be rendered as an image with an algorithm similar to Identicon.
1.2. All three kinds of representation of WID is identical.
2. Bits in WID has specified definitions:
2.1. Most-Significant-Bit (MSB) 0 - 1 are reserved bits.
2.2. MSB 2 - 11 are locale codes from ISO 3166 three digit codes (LB).
2.2.1. All unspecified codes in ISO 3166 can be used for constructed languages.
2.3. MSB 12 - 23 are Namespaces bit (NB).
2.4. MSB 24 is the Metadata linked indicator bit (MLIB).
2.5. MSB 25 - 107 are the article bits (AB).
2.5.1. AB are generated randomly for a new article, with an MLIB of 0.
2.5.2. If a new article has linked to Metadata, then AB will be re-written with a same article's AB with different locales, and MLIB will be set to 1.
2.5.3. Some MSB of AB can be used for user ID if NB shows this is a User Page.
2.6. MSB 108 - 127 are the article history bits (HB).
2.6.1. An HB with all 1 is the special representation of the current page.

Besides, a link to an article in LuaWiki can use a n URL containing the title or WID. Article redirection can use WID rather than article title.

**Comment by AlexanderMisel** [comment]
But why bother using a 128-bit interger for articles? We don't have to compress so much information in a single field; instead, we can use other fields to indicate namespaces and redirections. Also I think bit operations isn't that friendly with database indices.

**Comment by Geno1024** [comment]
OK.
