### ISSUE TITLE
Single Lua entrypoint instead of multiple Lua file managed by Nginx.

### ISSUE THREAD

**Issue by Geno1024** [AlexanderMisel/LuaWiki#11]
Easier hot reloading?

**Comment by AlexanderMisel** [comment]
I think managing routes by Nginx will be faster than single lua entrypoint, although there are ways to manage routes described [here](https://github.com/bungle/awesome-resty#routing-libraries). However I haven't tested them.

**Comment by AlexanderMisel** [comment]
API routes can be combined to the same prefix `/api`so that we can manage all API routes by Lua. Currently I manage all paths by nginx configuration for simplicity.
